service: aws
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler

custom:
  esbuild:
    packager: pnpm
    external:
      - '@sparticuz/chromium'
